"use client"

import './globals.css'
import { Montserrat } from 'next/font/google'
import { ThemeProvider } from "next-themes"
import Navbar from "@/components/Navbar"

const montserrat = Montserrat({ 
  subsets: ["latin"], 
  variable: "--font-montserrat"
})

export const metadata = {
  title: 'Dan Levison | Front-End Developer ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-mont`}>
        <ThemeProvider attribute="class">
          <Navbar /> 
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
